name: Deploy Flask App to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10  # Use your preferred Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create production build
      run: |
        mkdir -p build
        echo "from main import app" > build/wsgi.py
        echo "if __name__ == '__main__': app.run(host='0.0.0.0', port=8080)" >> build/wsgi.py

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
